---
name: Feature Request
description: Submit a feature request to help improve this project.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request! 🙌
  - type: textarea
    attributes:
      label: 💡 Description
      description: Describe clearly and concisely the feature you would like to see implemented.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: macOS Version
      description: What version of macOS are you running?
      options:
        - macOS Sequoia 15
        - macOS Sonoma 14
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Favorite or favourite?
      description: |
        I confirm that the word is correctly spelt **favourite** :flag-ca: :flag-au:
      options:
        - label: "Yes"
          required: true
